### ISSUE TITLE
Review for joss

### ISSUE THREAD

**Issue by ibarraespinosa** [adithirgis/OpenSourceAirQualityApp#1]
hello @adithirgis, how are you? I hope everything is fine.

I`m starting this issue to review your article, according to the guidelines suggestions as mentioned here https://github.com/openjournals/joss-reviews/issues/3435

I will be editing this issue and adding more items as my review progress.

### [Checklist The JOSS paper](https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper)

- [x] A list of the authors of the software and their affiliations.
- [x] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [x] A clear statement of need that illustrates the purpose of the software.
- [x] A description of how this software compares to other commonly-used packages in this research area.
- [x] Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it.
- [x] A list of key references including a link to the software archive.
- [x] Note the paper should not include software documentation such as API (Application Programming Interface) functionality, as this should be outlined in the software documentation.

### [Checklist license](https://joss.readthedocs.io/en/latest/review_criteria.html#software-license)
- [x] Acceptable: A plain-text LICENSE or COPYING file with the contents of an OSI approved license

### [Checklist Substantial scholarly effort](https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort)

- [x] Age of software (is this a well-established software project) / length of commit history.
- [x] Number of commits.
- [x] Number of authors.
- [x] Lines of code (LOC): These statistics are usually reported by Whedon in the pre-review issue thread.
- [x] Whether the software has already been cited in academic papers.
- [x] Whether the software is sufficiently useful that it is likely to be cited by other researchers working in this domain.

### [Statement of need](https://joss.readthedocs.io/en/latest/review_criteria.html#a-statement-of-need)

- [x] The authors should clearly state what problems the software is designed to solve and who the target audience is

### [Tests](https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

- [x] An automated test suite hooked up to an external service such as Travis-CI or similar

### [Autorship](https://joss.readthedocs.io/en/latest/review_criteria.html#authorship)

- [x] Indicate what authors did

**Comment by adithirgis** [comment]
Hi @ibarraespinosa!

I am doing good, hope you are doing well too.

Thanks for reviewing this!

**Comment by ibarraespinosa** [comment]
Hello @adithirgis 

i have been trying to download from CCR but I can't. I only got a message saying "Processing". I think you package is very useful and I'm wondering if I can use with my own data. 

![Screenshot from 2021-07-14 12-37-15](https://user-images.githubusercontent.com/27447280/125651316-65ec0dd5-955c-45f0-9f6e-81a1428d6afc.png)

Do you have a sample data?

Then, I downloaded your data and open it with LibreOffice, finding that it includes row.names. Did you use row.names = T when you generate the csv?
![Screenshot from 2021-07-14 12-43-05](https://user-images.githubusercontent.com/27447280/125651559-42916c20-36cf-407a-9896-d73f370577d6.png)

**Comment by adithirgis** [comment]
Hello!


Thank you for reviewing the application.
1. Sorry the site where you download CCR, sometimes has issues, you can try
clicking the excel option again and see if it downloads. I am attaching a
few hourly files from CCR and from OpenAir and AirNow to explore.
2. I have not added *row.names = TRUE*. I could take a look into that.

Cheers!
Adithi

**Comment by adithirgis** [comment]
Hello!


Thank you for reviewing the application.
1. Sorry the site where you download CCR, sometimes has issues, you can try clicking the excel option again and see if it downloads. I am adding a few hourly files [here](https://github.com/adithirgis/pollucheck/tree/main/inst/shiny/data_check) from CCR and from OpenAir and AirNow to explore.
2. I have not added `row.names = TRUE`. I could take a look into that.

Cheers!
Adithi

**Comment by adithirgis** [comment]
Hi,

Just wondering if we have have multiple reviews here and in the [issues of JOSS](https://github.com/openjournals/joss-reviews/issues/3435).

Thanks!

**Comment by ibarraespinosa** [comment]
Hi,

Just one review. Here is more like a personal review based on JOSS
guidelines. The official review is here
https://github.com/openjournals/joss-reviews/issues/3435.

Em qui., 15 de jul. de 2021 às 01:34, Adithi R. Upadhya <
***@***.***> escreveu:

**Comment by ibarraespinosa** [comment]
### Observations of the manuscript: 

General: This a great work and I'm interested in sharing with colleagues who work with observations.  The only issues us that the manuscript shows a description of the API rather than paper. In this sense it would be nice to add an example and its explanations. For instance, on Line 53 you mention that the ratio PM2.5/PM10 is a useful metric on air pollution field but you do not mention why. Then, my suggestion is to add a section analyzing a case of air pollution, using and explaining some of the tools that you have developed. Again, this is a suggestion only.  

L8: I don't understand the word *device*. You mean promote?
L13: Is quantum appropriate?

**Comment by ibarraespinosa** [comment]
I`m having lots of fun with this package. AIRNOW works perfectly, but I cant upload OpenAQ data. What are the restrictions, min 15-min?

**Comment by ibarraespinosa** [comment]
Add a [CrediT](https://www.elsevier.com/authors/policies-and-guidelines/credit-author-statement) statement mentioning what authors did

**Comment by ibarraespinosa** [comment]
Please, add tests.

**Comment by adithirgis** [comment]
Hello, 

Thanks for the review, here are the tests - https://github.com/adithirgis/pollucheck/tree/main/inst/shiny/tests/shinytest.

**Comment by adithirgis** [comment]
> Add a CrediT statement mentioning what authors did

We have added the roles of the authors in the [DESCRIPTION](https://github.com/adithirgis/pollucheck/blob/main/DESCRIPTION) file, do we need to add anymore?

**Comment by adithirgis** [comment]
> I`m having lots of fun with this package. AIRNOW works perfectly, but I cant upload OpenAQ data. What are the restrictions, min 15-min?

So, the options/restrictions for CCR are 15, 30 and 60 min only, while for OpenAQ there are no options or restrictions, I am afraid if the CCR option is checked.

**Comment by ibarraespinosa** [comment]
> > Add a CrediT statement mentioning what authors did
> 
> We have added the roles of the authors in the [DESCRIPTION](https://github.com/adithirgis/pollucheck/blob/main/DESCRIPTION) file, do we need to add anymore?



> > I`m having lots of fun with this package. AIRNOW works perfectly, but I cant upload OpenAQ data. What are the restrictions, min 15-min?
> 
> So, the options/restrictions for CCR are 15, 30 and 60 min only, while for OpenAQ there are no options or restrictions, I am afraid if the CCR option is checked.

[measurements_2.csv](https://github.com/adithirgis/pollucheck/files/6824584/measurements_2.csv)
I cant make it work with this file

**Comment by adithirgis** [comment]
Let me try this. Thanks!

**Comment by adithirgis** [comment]
Hello! 

Were you able to work with the CCR data?

And was I able to respond to these following comments correctly? (Sorry I am a little confused)

> Please, add tests.

> Add a CrediT statement mentioning what authors did


Thanks!

**Comment by adithirgis** [comment]
Hello, 

>measurements_2.csv
I cant make it work with this file

Thanks so much for pointing it out. I hope it works now :)

**Comment by adithirgis** [comment]
> L8: I don't understand the word device. You mean promote?
L13: Is quantum appropriate?

I have changed device to **_facilitate_** and quantum to **_amount_**.

**Comment by adithirgis** [comment]
> Add a CrediT statement mentioning what authors did

Where should I add this statement?

Adithi R. Upadhya created the package and contributed to the manuscript and she will maintain the package with Meenakshi Kushwaha who also supervised and contributed to the manuscript, Pratyush Agrawal contributed to designing, testing the application and data collection while Sreekanth Vakacherla designed, contributed to the manuscript and supervised the project.

**Comment by adithirgis** [comment]
> Line 53 you mention that the ratio PM2.5/PM10 is a useful metric on air pollution field but you do not mention why.

We have added the reasons along with references in manuscript, thank you for pointing it out. 

"the app computes the PM2.5/PM10 ratio, a useful metric in the air pollution field to identify sources of PM and to estimate PM2.5 when only PM10 is available [Chan:2008; Chu:2015; Spandana:2021]."

**Comment by adithirgis** [comment]
> my suggestion is to add a section analyzing a case of air pollution, using and explaining some of the tools that you have developed. 

We are working on this. Thank you

**Comment by ibarraespinosa** [comment]
It would be nice to identify the units on the data-base and add it on the plot, keeping the option Edit Y axis label

**Comment by adithirgis** [comment]
I am sorry but some files downloaded from CCR does not have units attached in the raw file. Any suggestions we should hard code it?

Thanks!

**Comment by ibarraespinosa** [comment]
In that case it is hard. However, if it is possible, you could make default
reading the units from the database, and if the units is not available, the
you could just add "units" or something. I will check your code

Em sáb, 17 de jul de 2021 01:58, Adithi R. Upadhya ***@***.***>
escreveu:

**Comment by adithirgis** [comment]
Hello @ibarraespinosa, 

Should I change the Y axis label values everywhere instead of **Y parameter**  to **Y parameter (units)**?

And also have we been able to respond to your previous comments?

Thanks 
Adithi

**Comment by ibarraespinosa** [comment]
Hello Adithirgis,

I am not sure. It would be fine that your program detect automatically the
untis. If that is not possible you can keep it as it is. YEah, all your
comments are good so far.

Have a nice week.


Best, Sergio

Em seg., 19 de jul. de 2021 às 02:57, Adithi R. Upadhya <
***@***.***> escreveu:

**Comment by adithirgis** [comment]
Thanks for the quick response. 

I was trying to make it work, but it seems like it would be difficult to add for CCR files. I hope this is ok. Thanks so much for your review. We really appreciate it. 

Where should we add the credit statement? 

Also we are almost completing with the case study, I will update in the paper.md soon.

**Comment by ibarraespinosa** [comment]
> > Add a CrediT statement mentioning what authors did
> 
> Where should I add this statement?
> 
> Adithi R. Upadhya created the package and contributed to the manuscript and she will maintain the package with Meenakshi Kushwaha who also supervised and contributed to the manuscript, Pratyush Agrawal contributed to designing, testing the application and data collection while Sreekanth Vakacherla designed, contributed to the manuscript and supervised the project.

You can include initials, but it is fine.

**Comment by adithirgis** [comment]
In the paper.md or in the ReadMe file?

We will wait for the review to finish in https://github.com/openjournals/joss-reviews/issues/3435

Thanks

**Comment by ibarraespinosa** [comment]
> In the paper.md or in the ReadMe file?
> 
> We will wait for the review to finish in [openjournals/joss-reviews#3435](https://github.com/openjournals/joss-reviews/issues/3435)
> 
> Thanks

For me it is fine, the paper and the software are already very good. Just try to fix the problem with the upload of openAQ.
For me the revision is over.

You have developed another great software to address air pollution problems. I hope you can publish many papers using pollucheck. I`m sure it will be used around the globe.

Best, Sergio

**Comment by adithirgis** [comment]
Oh thanks so much, we have addressed the OpenAQ issue, please let us know if you still face same issue.
