### ISSUE TITLE
Original analysis dataset?

### ISSUE THREAD

**Issue by Fil** [adithirgis/OpenSourceAirQualityApp#4]
Hello,

can you clarify what “BP” means in the “Time variation plot”? This parameter doesn't seem to be present in the test datasets. Thank you!

**Comment by adithirgis** [comment]
Hello @Fil! 
Thanks for your question. 

**BP** is Barometric Pressure which is available at this [site](https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing/data) for download. The unit is _mmHg_. And yes we did not add in the test data (was only used for the screenshot). You can download BP from the site mentioned above. 

I hope we were able to resolve your issue. Let us know if you have any more queries.

Cheers!
Adithi

**Comment by Fil** [comment]
Thank you for the clarification. It's true that atmospheric pressure and temperature make the nicest cycles :-)
